CREATE SCHEMA IF NOT EXISTS  `mstar_supplychain` DEFAULT CHARACTER SET utf8mb4;

USE `mstar_supplychain`;

CREATE TABLE IF NOT EXISTS `mstar_supplychain`.`commodity_type` (
  `NAME_` VARCHAR(50) NOT NULL,
  `DESCRIPTION_` VARCHAR(500) NULL,
  PRIMARY KEY (`NAME_`));

CREATE TABLE IF NOT EXISTS `mstar_supplychain`.`manufacturer` (
  `CPF_CNPJ_` VARCHAR(14) NOT NULL,
  `NAME_` VARCHAR(256) NOT NULL,
  `DESCRIPTION_` VARCHAR(1000) NULL,
  `ADDRESS_` VARCHAR(512) NOT NULL,
  PRIMARY KEY (`CPF_CNPJ_`));

CREATE TABLE IF NOT EXISTS `mstar_supplychain`.`commodity` (
  `REGISTRATION_NUMBER_` INT NOT NULL,
  `NAME_` VARCHAR(200) NOT NULL,
  `DESCRIPTION_` VARCHAR(1000) NOT NULL,
  `STOCK_AMOUNT_` INT UNSIGNED NOT NULL DEFAULT 0,
  `MANUFACTURER_RN_` VARCHAR(14) NOT NULL,
  `TYPE_` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`REGISTRATION_NUMBER_`),
  INDEX `fk_commodity_MANUFACTURER_RN_manufacturer_CPF_CNPJ_idx` (`MANUFACTURER_RN_` ASC) INVISIBLE,
  INDEX `fk_commodity_TYPE_commodity_type_NAME_idx` (`TYPE_` ASC) VISIBLE,
  CONSTRAINT `fk_commodity_MANUFACTURER_RN_manufacturer_CPF_CNPJ`
    FOREIGN KEY (`MANUFACTURER_RN_`)
    REFERENCES `mstar_supplychain`.`manufacturer` (`CPF_CNPJ_`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_commodity_TYPE_commodity_type_NAME`
    FOREIGN KEY (`TYPE_`)
    REFERENCES `mstar_supplychain`.`commodity_type` (`NAME_`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);
